---
- name: Start fully connected Jacktrip Mesh
  hosts: bikes
  gather_facts: false
  become: true

  vars:
    soundscape: "rainforest"
    remote_app_dir: "/home/{{ ansible_user }}/Desktop/BIKES/concepts/soundscapes"
    p2psc_dir: "/home/{{ ansible_user }}/.local/bin/p2psc"
    gui_user: "{{ ansible_user }}"

  
  tasks:
    - name: Show resolved remote app directory
      debug:
        msg: "Host {{ ansible_user }} using remote_app_dir={{ remote_app_dir }}"

    - name: Show resolved ansible directory
      debug:
        msg: "Host {{ p2psc_dir }} using remote_app_dir={{ remote_app_dir }}"

    - name: Kill all SuperCollider things
      command: killall -9 sclang scsynth
      ignore_errors: true

    - name: Kill p2psc
      command: killall -9 p2psc
      ignore_errors: true

    - name: Kill all JackTrip things
      command: killall -9 jacktrip
      ignore_errors: true

    - name: Kill all qjacks
      command: killall -9 qjackctl
      ignore_errors: true

    - name: Kill all jackd things
      command: killall -9 jackd
      ignore_errors: true

    - name: Kill all python3 things
      command: killall -9 python3
      ignore_errors: true

    - name: Start jack
      become: false
      shell: |
        jackd -d alsa -d hw:2,0 &
      async: 2592000
      poll: 0
    
    - name: Pause briefly 
      pause:
        seconds: 2

    - name: Start p2psc
      become: false
      shell: |
        {{ p2psc_dir }} &
      async: 2592000
      poll: 0

    - name: Pause briefly to let p2psc start
      pause:
        seconds: 2


    - name: Run SC script
      become: false
      shell: |
        cd "{{ remote_app_dir }}" && \
        env \
          HOME="/home/{{ ansible_user }}" \
          DISPLAY=":0" \
          XAUTHORITY="/home/{{ ansible_user }}/.Xauthority" \
          nohup sclang "{{ remote_app_dir }}/GUIListener.scd" "{{ soundscape }}" &
      async: 2592000
      poll: 0

    - name: Wait for scsynth to appear
      shell: pgrep -af scsynth
      register: scsynth_check
      retries: 10
      delay: 1
      until: scsynth_check.rc == 0

    - name: Extra pause for JACK to settle
      pause:
        seconds: 5

    - name: Launch GUI script
      shell: |
        cd "{{ remote_app_dir }}" && \
        sudo -u "{{ gui_user }}" env \
          DISPLAY=:0 \
          XAUTHORITY="/home/{{ gui_user }}/.Xauthority" \
          nohup python3 "{{ remote_app_dir }}/PixelGUI.py" "{{ soundscape }}" &
      async: 2592000
      poll: 0