---
- name: Force-install python packages with pip (no venv)
  hosts: all
  become: true

  tasks:

    - name: Ensure pip is installed
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-wheel
        state: present
        update_cache: yes

    - name: Install python-osc and pygame system-wide
      command: >
        pip3 install
        python-osc
        pygame
        --break-system-packages

        